name: CI

on: [push]

jobs:
  eslint-jest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5402:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
        working-directory: ./app
      - name: Run ESLint
        run: yarn lint
        working-directory: ./app
      - name: Run Migrate
        run: yarn migrate:postgres
        working-directory: ./app
      - name: Run Unit & Integration Test
        run: yarn test
        working-directory: ./app
        env:
          POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
